ErdaldanisEDU/Models/EgitmenEkle.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErdaldanisEDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitmenEkle
    {
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string bolum { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int egitmenId { get; set; }
        public string fakulte { get; set; }
    }
}

ErdaldanisEDU/Controllers/YoneticiController.cs
using ErdaldanisEDU.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace ErdaldanisEDU.Controllers
{
    
    [ControlLogin]
    public class YoneticiController : Controller
    {
        ErdaldanisEDUdb erdaldanis = new ErdaldanisEDUdb();
        public ActionResult Anasayfa()
        {
            return View();

        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Egitmenler()
        {
            List<EgitmenEkle> kayitListe = erdaldanis.EgitmenEkle.ToList();
            return View(kayitListe);
           
        }

        public ActionResult EgitmenEkle()
        {


            return View();
            

        }
        
        
        [HttpPost]
        public ActionResult EgitmenEkle(EgitmenEkle egitmen)
        {
            EgitmenEkle kayit = new EgitmenEkle();
            kayit.adi = egitmen.adi;
            kayit.soyadi = egitmen.soyadi;
            kayit.bolum = egitmen.bolum;
            kayit.username = egitmen.username;
            kayit.email = egitmen.email;
            kayit.password = egitmen.password;
            kayit.fakulte = egitmen.fakulte;

            erdaldanis.EgitmenEkle.Add(kayit);
            erdaldanis.SaveChanges();
            ViewBag.sonuc = "Kayıt Yapıldı";
            return View();

        }
       
        public ActionResult EgitmenDuzenle(int? id)
        {
            EgitmenEkle kayit = erdaldanis.EgitmenEkle.Where(k => k.egitmenId == id).SingleOrDefault();

            EgitmenEkle egitmen = new EgitmenEkle()
            {
                egitmenId = kayit.egitmenId,
                adi = kayit.adi,
                soyadi = kayit.soyadi,
                bolum = kayit.bolum,
                username = kayit.username,
                email = kayit.email,
                password = kayit.password,
                fakulte = kayit.fakulte
            };


            return View(egitmen);

        }
        
        public ActionResult EgitmenSil(int? id)
        {
            EgitmenEkle kayit = erdaldanis.EgitmenEkle.Where(k => k.egitmenId == id).SingleOrDefault();

            erdaldanis.EgitmenEkle.Remove(kayit);
            erdaldanis.SaveChanges();
            return RedirectToAction("Egitmenler");
        }

        [HttpPost]
        public ActionResult EgitmenDuzenle(EgitmenEkle ekle)
        {
            EgitmenEkle kayit = erdaldanis.EgitmenEkle.Where(k => k.egitmenId == ekle.egitmenId).SingleOrDefault();

            kayit.adi = ekle.adi;
            kayit.soyadi = ekle.soyadi;
            kayit.bolum = ekle.bolum;
            kayit.username = ekle.username;
            kayit.email = ekle.email;
            kayit.password = ekle.password;
            kayit.fakulte = ekle.fakulte;
            erdaldanis.SaveChanges();
            return View();
        }









    }
}

ErdaldanisEDU/Views/Yonetici/About.cshtml
@{
    
} 

ErdaldanisEDU/Views/Yonetici/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ErdaldanisEDU/Views/Yonetici/EgitmenDuzenle.cshtml
@model ErdaldanisEDU.Models.EgitmenEkle

@{

}
<div class="container-fluid">

    <!-- left column -->
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h2 class="card-title"> Kayıt Güncelle</h2>
            </div>
        <div class="card-body">
            @using (Html.BeginForm("EgitmenDuzenle", "Yonetici", FormMethod.Post))
            {
                @Html.HiddenFor(k => k.egitmenId)
                @Html.DisplayName("Adı")
                @Html.TextBoxFor(k => k.adi, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.adi, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("Soyadı")<br />
                @Html.TextBoxFor(k => k.soyadi, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.soyadi, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("Bölümü")<br />
                @Html.TextBoxFor(k => k.bolum, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.bolum, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("Kullanıcı Adı")<br />
                @Html.TextBoxFor(k => k.username, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.username, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("E-Postası")<br />
                @Html.TextBoxFor(k => k.email, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.email, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("Parolası")<br />
                @Html.TextBoxFor(k => k.password, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.password, null, new { @class = "text-danger" })<br />
                @Html.DisplayName("Fakülte")<br />
                @Html.TextBoxFor(k => k.fakulte, new { @class = "form-control" })
                @Html.ValidationMessageFor(k => k.fakulte, null, new { @class = "text-danger" })<br />

                <br />
                if (ViewBag.sonuc != null)
                {
                    <div class="alert alert-success"> @ViewBag.sonuc</div>
                }
                <input type="submit" value="Güncelle" class="btn btn-success" />
            }
        </div>
        </div>
    </div>

ErdaldanisEDU/Views/Yonetici/EgitmenEkle.cshtml
@model ErdaldanisEDU.Models.EgitmenEkle

@{


}
    <div class="container-fluid">

        <!-- left column -->
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h2 class="card-title"> Eğitmen Ekle - ErdaldanisEDU</h2>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EgitmenEkle", "Yonetici", FormMethod.Post))
                {


                    @Html.DisplayName("Adı")
                    @Html.TextBoxFor(k => k.adi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.adi, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("Soyadı")<br />
                    @Html.TextBoxFor(k => k.soyadi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.soyadi, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("Bölümü")<br />
                    @Html.TextBoxFor(k => k.bolum, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.bolum, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("Kullanıcı Adı")<br />
                    @Html.TextBoxFor(k => k.username, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.username, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("E-Postası")<br />
                    @Html.TextBoxFor(k => k.email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.email, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("Parolası")<br />
                    @Html.TextBoxFor(k => k.password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.password, null, new { @class = "text-danger" })<br />
                    @Html.DisplayName("Fakülte")<br />
                    @Html.TextBoxFor(k => k.fakulte, new { @class = "form-control" })
                    @Html.ValidationMessageFor(k => k.fakulte, null, new { @class = "text-danger" })<br />

                    <br />
                    if (ViewBag.sonuc != null)
                    {
                        <div class="alert alert-success"> @ViewBag.sonuc</div>
                    }
                    <input type="submit" value="Kaydet" class="btn btn-success" />
                }
            </div>
            </div>
        </div>

ErdaldanisEDU/Views/Yonetici/Egitmenler.cshtml
@model IEnumerable<ErdaldanisEDU.Models.EgitmenEkle>
@{
}
    <div class="container-fluid">

        <!-- left column -->
        <!-- general form elements -->
        <div class="card card-primary">
            @Html.ActionLink("Yeni Kayıt", "EgitmenEkle", null, new { @class = "btn btn-primary" })<br />




            <table class="table">
                <tr>
                    <td>KN</td>
                    <td>Adı</td>
                    <td>Soyadi</td>
                    <td>Fakülte</td>
                    <td>Bolum</td>
                    <td>Kullanıcı Adı </td>
                    <td>E-Posta</td>
                    <td>Parola</td>
                    <td>Düzenle</td>
                    <td>Sil</td>


                </tr>
                @foreach (var kayit in Model)
                {
                    <tr>
                        <td>@kayit.egitmenId</td>
                        <td>@kayit.adi</td>
                        <td>@kayit.soyadi</td>
                        <td>@kayit.fakulte</td>
                        <td>@kayit.bolum</td>
                        <td>@kayit.username</td>
                        <td>@kayit.email</td>
                        <td>@kayit.password</td>
                        <td>@Html.ActionLink("Düzenle", "EgitmenDuzenle", new { id = kayit.egitmenId }, new { @class = "btn btn-warning" })</td>
                        <td>@Html.ActionLink("Sil", "EgitmenSil", new { id = kayit.egitmenId }, new { @class = "btn btn-warning" })</td>
                    </tr>
                }

            </table>
        </div> </div> </div>